import React from 'react';
import { render, screen } from '@testing-library/react';
import KittyList from './kitty-list';

beforeAll(() => {
    jest.useFakeTimers();
});

afterAll(() => {
    jest.useRealTimers();
});

test('Render h1 title', () => {
    render(<KittyList />);
    const titleElement = screen.getByText(/Gelato Kitties/i);
    expect(titleElement).toBeInTheDocument();
});

/* NOTES:
 * - Test if Dark Mode is working by clicking the button and checking a class or a color has changed
 * - Test CategoriesFilter by checking number of present tab items generated by generateTaxonomy Service
 * - Mock a kitty call with a number of responses, and expect the same number of elements rendered in the SimpleGrid
 *  */
